### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by jakevis** [simplextech/udi-poly-ecowitt#1] opened 2021-02-22 19:19 UTC
Hi there - firstly, thank you very much for publishing this. I have found what I think is a bug. I am using N8N to duplicate my request from a GW1000 (N8N takes the request, writes to a file, sends it to my weather station site, and sends it to Polisy).

Data is making it into Polisy fine, but I dont think its returning a status code.

This is what Polisy is seeing:
`host: 192.168.1.66:8080
content-type: application/x-www-form-urlencoded
accept-encoding: gzip, deflate
content-length: 293
Connection: close
2021-02-22 11:14:36,230 NodeServer polyinterface      DEBUG    polyinterface:write: PASSKEY=XXXXXXXX&stationtype=GW1000B_V1.6.3&dateutc=2021-02-22%2019%3A14%3A34&tempinf=73.8&humidityin=46&baromrelin=29.796&baromabsin=29.796&temp1f=53.42&humidity1=71&temp2f=62.78&humidity2=50&temp3f=72.50&humidity3=45&batt1=0&batt2=0&batt3=0&freq=915M&model=GW1000_Pro
2021-02-22 11:14:36,231 NodeServer polyinterface      INFO     polyinterface:reportDriver: Updating Driver indoor - CLITEMP: 73.8, uom: 17
2021-02-22 11:14:36,234 NodeServer polyinterface      INFO     polyinterface:reportDriver: Updating Driver wh31_2 - CLITEMP: 62.78, uom: 17
2021-02-22 11:14:36,236 NodeServer polyinterface      INFO     polyinterface:reportDriver: Updating Driver wh31_3 - CLITEMP: 72.50, uom: 17`

But on N8N - I get this error:

`[
{
"error": {
"name": "RequestError",
"message": "Error: socket hang up",
"cause": {
"code": "ECONNRESET"
},
"error": {
"code": "ECONNRESET"
},
"options": {
"headers": {
"accept": "application/json,text/html,application/xhtml+xml,application/xml,text/*;q=0.9, */*;q=0.1"
},
"method": "POST",
"uri": "http://192.168.1.66:8080/data/report/",
"gzip": true,
"rejectUnauthorized": true,
"form": {
"PASSKEY": "XXXXXXXXXXXXXXXX",
"stationtype": "GW1000B_V1.6.3",
"dateutc": "2021-02-22 19:14:34",
"tempinf": "73.8",
"humidityin": "46",
"baromrelin": "29.796",
"baromabsin": "29.796",
"temp1f": "53.42",
"humidity1": "71",
"temp2f": "62.78",
"humidity2": "50",
"temp3f": "72.50",
"humidity3": "45",
"batt1": "0",
"batt2": "0",
"batt3": "0",
"freq": "915M",
"model": "GW1000_Pro"
},
"json": true,
"simple": true,
"resolveWithFullResponse": false,
"transform2xxOnly": false
}
}
}
]`

I assume Polisy just needs to return 200 to fix this.

Thanks again,

Jake

**Comment by jakevis** [comment] 2021-02-22 19:29
Actually looks like the code is in there to handle this 😊 - just commented out:
https://github.com/simplextech/udi-poly-ecowitt/blob/a0d6a20cfa0e2dc8c7c6eabd4a5c05e6ccf776a1/ecowitt.py#L816

**Comment by simplextech** [comment] 2021-02-25 04:10
Please update the server.json in your forked version to reflect that it's not a Simplex Technology provided version.

**Comment by simplextech** [comment] 2021-02-25 05:02
I merged your PR.  I'll post an update note on the forum about the known error and those that scour the logs can deal with it for now.  This is likely the last update minus bug fixes I'll perform on this version as the plan is to migrate to the JS interface.

**Closed as completed by simplextech** 2021-02-25 05:02 UTC

**Comment by jakevis** [comment] 2021-02-25 05:38
> Please update the server.json in your forked version to reflect that it's not a Simplex Technology provided version.

If your taking the PR ill just delete my folk once done. Thanks for this.

Cheers,

**Comment by simplextech** [comment] 2021-02-25 14:18
You can keep your fork.

Deleting your fork will not remove/update/change that it's been published to the UDI NodeServer Store.  Now the store is throwing errors because the repo is gone.  Please work with UDI support to now remove your copy from the Polyglot store.

FYI - In future for forks and not public versions you can install them directly without publishing to the store.


John Eubanks
Phone:  304-596-1136
[simplex-logo-256.png] [https://www.simplextech.net]

[https://www.simplextech.net]
https://www.simplextech.net [https://www.simplextech.net/]
The content of this message is confidential. If you have received it by mistake, please inform us by an email reply and then delete the message. It is forbidden to copy, forward, or in any way reveal the contents of this message to anyone. The integrity and security of this email cannot be guaranteed over the Internet. Therefore, the sender will not be held liable for any damage caused by the message.
On 2/25/2021 0:40:16, Jake Vis <notifications@github.com> wrote:
Please update the server.json in your forked version to reflect that it's not a Simplex Technology provided version.
If your taking the PR ill just delete my folk once done. Thanks for this.
Cheers,

**Comment by jakevis** [comment] 2021-02-25 14:56
I actually didn't push it to the store... Forked and worked locally. I'll reach out to them and see what's going on.

**Comment by jakevis** [comment] 2021-02-25 20:50
All fixed :) 

![image](https://user-images.githubusercontent.com/10895705/109215440-0343a100-7768-11eb-885c-7f5d92e50320.png)

Thank you again @simplextech for your work and intergrations
